import React, { useState, useEffect, useRef } from "react";
import { SubtitleCue } from "../types/platform";
import studioBackdrop from "../assets/images/studio_video_frame_scene_1791234612036.jpg";
import {
  Play,
  Pause,
  RotateCcw,
  Download,
  Sparkles,
  Upload,
  Plus,
  Trash2,
  Film,
  Code2,
  Package,
  Sliders,
  Webhook,
  CheckCircle2,
  Copy,
} from "lucide-react";

interface WasmStudioViewProps {
  initialCues: SubtitleCue[];
  onRefreshState: () => void;
}

export const WasmStudioView: React.FC<WasmStudioViewProps> = ({
  initialCues,
  onRefreshState,
}) => {
  const [cues, setCues] = useState<SubtitleCue[]>(initialCues);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [currentTime, setCurrentTime] = useState<number>(1.2);
  const duration = 16.0;

  // Video source (optional user local video upload)
  const [customVideoUrl, setCustomVideoUrl] = useState<string | null>(null);
  const [videoTitle, setVideoTitle] = useState<string>(
    "Cyberpunk_NeoTokyo_Ep05_Master.mkv"
  );
  const [showBilingual, setShowBilingual] = useState<boolean>(true);
  const [activeDevModule, setActiveDevModule] = useState<
    "sdk" | "packager" | "builder" | "webhook"
  >("sdk");

  // AI Transcribe & Translate Input
  const [sourceLang, setSourceLang] = useState<string>("ja-JP");
  const [stylePreset, setStylePreset] = useState<
    "CyberNeon" | "KaraokeFX" | "Default" | "SignTop"
  >("CyberNeon");
  const [rawScriptInput, setRawScriptInput] = useState<string>(
    `[00:00.50 - 00:03.80] Kaito: 夜明け前のネオ東京、すべての信号がエッジゲートウェイに集まる。\n[00:04.00 - 00:07.50] Aoi: HMAC-SHA256認証完了。WASM SubtitlesOctopusエンジン、起動します。\n[00:07.80 - 00:11.60] Sign: WARNING: HIGH-SPEED SUBTITLE STREAM SYNCING TO CLOUDFLARE R2\n[00:11.80 - 00:16.00] Kaito: 7層アーキテクチャが完全にリンクした。今からハードサブ出力を開始する！`
  );
  const [isAiProcessing, setIsAiProcessing] = useState<boolean>(false);
  const [isExportingR2, setIsExportingR2] = useState<boolean>(false);
  const [studioNotice, setStudioNotice] = useState<string | null>(null);
  const [copiedCode, setCopiedCode] = useState<boolean>(false);

  // App Packager / Builder settings
  const [packagerTarget, setPackagerTarget] = useState<
    "tauri" | "pwa" | "capacitor"
  >("tauri");
  const [wasmMemoryMb, setWasmMemoryMb] = useState<number>(512);
  const [renderFps, setRenderFps] = useState<number>(60);

  const videoRef = useRef<HTMLVideoElement | null>(null);

  useEffect(() => {
    if (initialCues && initialCues.length > 0) {
      setCues(initialCues);
    }
  }, [initialCues]);

  // Playback timer loop
  useEffect(() => {
    if (!isPlaying) return;
    const interval = window.setInterval(() => {
      setCurrentTime((prev) => {
        const next = prev + 0.1;
        if (next >= duration) {
          return 0;
        }
        return Number(next.toFixed(2));
      });
    }, 100);
    return () => window.clearInterval(interval);
  }, [isPlaying]);

  const activeCues = cues.filter(
    (c) => currentTime >= c.startSec && currentTime <= c.endSec
  );

  const handleVideoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const url = URL.createObjectURL(file);
    setCustomVideoUrl(url);
    setVideoTitle(file.name);
    setStudioNotice(`Đã nạp video cục bộ '${file.name}' vào bộ dựng WASM SubtitlesOctopus.`);
  };

  const handleRunAiVietsub = async () => {
    setIsAiProcessing(true);
    setStudioNotice(null);
    try {
      const response = await fetch("/api/vietsub/ai-process", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sourceText: rawScriptInput,
          sourceLang,
          stylePreset,
          videoTitle,
        }),
      });
      const data = await response.json();
      if (data.ok && Array.isArray(data.cues)) {
        setCues(data.cues);
        setCurrentTime(data.cues[0]?.startSec ?? 0.6);
        setStudioNotice(
          `AI Vietsub Engine (Whisper STT + Gemini Translation) đã sinh ${data.cues.length} câu phụ đề .ASS chuẩn thời gian thực.`
        );
        onRefreshState();
      } else {
        setStudioNotice(data.error || "Không thể xử lý phụ đề AI.");
      }
    } catch {
      setStudioNotice("Lỗi kết nối tới dịch vụ AI Vietsub.");
    } finally {
      setIsAiProcessing(false);
    }
  };

  const generateAssFileContent = (): string => {
    const header = `[Script Info]
; Script generated by CyberSub Edge WASM Studio (SubtitlesOctopus Engine)
Title: ${videoTitle}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Plus Jakarta Sans,42,&H00FFFFFF,&H0000FFFF,&H00141008,&H80000000,-1,0,0,0,100,100,0,0,1,2.2,1.2,2,30,30,36,1
Style: CyberNeon,Plus Jakarta Sans,44,&H00F8FAFC,&H0038BDF8,&H00D97706,&H80000000,-1,0,0,0,100,100,0.5,0,1,2.5,1.5,2,30,30,38,1
Style: KaraokeFX,Plus Jakarta Sans,45,&H0034D399,&H00F1F5F9,&H000F172A,&H80000000,-1,0,0,0,100,100,0.5,0,1,2.6,1.5,2,30,30,40,1
Style: SignTop,JetBrains Mono,32,&H0038BDF8,&H00FFFFFF,&H000B0F17,&H90000000,-1,0,0,0,100,100,1,0,1,2.0,0,8,30,30,28,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
    const events = cues
      .map(
        (c) =>
          `Dialogue: 0,${c.start},${c.end},${c.style},${c.speaker},0,0,0,,${c.effectTag}${c.vietsubText}`
      )
      .join("\n");
    return header + events + "\n";
  };

  const handleDownloadAss = () => {
    const content = generateAssFileContent();
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${videoTitle.replace(/\.[^/.]+$/, "")}_Vietsub.ass`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setStudioNotice("Đã xuất file phụ đề chuẩn .ASS (SubStation Alpha v4.00+).");
  };

  const handlePushToFfmpegR2 = async () => {
    setIsExportingR2(true);
    setStudioNotice(null);
    try {
      const response = await fetch("/api/vietsub/export-hardsub", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          videoTitle,
          cues,
        }),
      });
      const data = await response.json();
      if (data.ok) {
        setStudioNotice(
          `Đã gửi file .ASS tới FFmpeg Hardsub Render Worker (Tier 5) và lưu trữ tại R2: ${data.r2Mp4Key}`
        );
        onRefreshState();
      }
    } finally {
      setIsExportingR2(false);
    }
  };

  const handleUpdateCueField = (
    id: string,
    field: keyof SubtitleCue,
    val: string | number
  ) => {
    setCues((prev) =>
      prev.map((c) => (c.id === id ? { ...c, [field]: val } : c))
    );
  };

  const handleAddCue = () => {
    const lastEnd = cues.length > 0 ? cues[cues.length - 1].endSec : 0;
    const newStart = Number((lastEnd + 0.2).toFixed(1));
    const newEnd = Number(Math.min(duration, newStart + 3.0).toFixed(1));
    const newCue: SubtitleCue = {
      id: `cue_${Date.now().toString().slice(-3)}`,
      start: `0:00:${newStart.toFixed(2).padStart(5, "0")}`,
      end: `0:00:${newEnd.toFixed(2).padStart(5, "0")}`,
      startSec: newStart,
      endSec: newEnd,
      speaker: "Narrator",
      originalText: "New subtitle segment added in WASM Studio.",
      vietsubText: "Phân đoạn phụ đề mới được thêm trực tiếp trên WASM Studio.",
      style: "CyberNeon",
      effectTag: "{\\fad(120,120)}",
    };
    setCues((prev) => [...prev, newCue]);
    setCurrentTime(newStart + 0.1);
  };

  const handleDeleteCue = (id: string) => {
    setCues((prev) => prev.filter((c) => c.id !== id));
  };

  const sdkSnippet = `import { SubtitlesOctopusWASM, EdgeSubtitleSync } from '@cyber/vietsub-sdk';

const studio = new SubtitlesOctopusWASM({
  videoElement: document.querySelector('#cyber-player'),
  subUrl: 'r2://cyber-media/subtitles/${videoTitle.replace(/\.[^/.]+$/, "")}.ass',
  fonts: ['r2://cyber-media/fonts/UVN-BanhMi-Bold-Karaoke.woff2'],
  wasmMemoryLimitMb: ${wasmMemoryMb},
  targetFps: ${renderFps},
  hmacGatewayEndpoint: 'https://edge.cybersub.vn/api/vietsub/sync'
});

await studio.mountAndRender();`;

  const handleCopySdk = () => {
    navigator.clipboard.writeText(sdkSnippet);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Studio Notice Banner */}
      {studioNotice && (
        <div className="flex items-center justify-between px-4 py-3 rounded-lg bg-sky-950/40 border border-sky-700/60 text-xs text-sky-200">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-sky-400 shrink-0" />
            <span>{studioNotice}</span>
          </div>
          <button
            onClick={() => setStudioNotice(null)}
            className="text-slate-400 hover:text-white px-2 whitespace-nowrap"
          >
            Đóng
          </button>
        </div>
      )}

      {/* Main Studio Grid: Left Video + WASM Canvas | Right AI Transcribe & Translate Engine */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left 7 Cols: SubtitlesOctopus WASM Video Viewport */}
        <div className="lg:col-span-7 bg-[#111827] border border-slate-800/90 rounded-lg overflow-hidden flex flex-col justify-between">
          <div className="px-5 py-3.5 border-b border-slate-800/80 flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <Film className="w-4 h-4 text-sky-400" />
              <span className="text-sm font-semibold text-slate-100">
                SubtitlesOctopus WASM C++ Client Renderer
              </span>
              <span className="text-xs text-slate-500 font-mono">
                · {renderFps} FPS · {wasmMemoryMb}MB Heap
              </span>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setShowBilingual(!showBilingual)}
                className={`px-2.5 py-1 text-xs rounded border transition-colors whitespace-nowrap ${
                  showBilingual
                    ? "bg-sky-500/15 border-sky-500/50 text-sky-300"
                    : "bg-[#0B0F17] border-slate-800 text-slate-400"
                }`}
              >
                Song Ngữ: {showBilingual ? "Bật" : "Tắt"}
              </button>

              <label className="inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 rounded cursor-pointer transition-colors whitespace-nowrap">
                <Upload className="w-3.5 h-3.5" />
                Nạp Video (.mp4/.webm)
                <input
                  type="file"
                  accept="video/mp4,video/webm"
                  onChange={handleVideoUpload}
                  className="hidden"
                />
              </label>
            </div>
          </div>

          {/* 16:9 Video + Live ASS Subtitle Render Stage */}
          <div className="relative aspect-video bg-[#070A10] overflow-hidden select-none">
            {customVideoUrl ? (
              <video
                ref={videoRef}
                src={customVideoUrl}
                className="w-full h-full object-cover"
                muted
                loop
              />
            ) : (
              <div className="w-full h-full relative bg-gradient-to-br from-slate-900 via-[#0B1324] to-slate-950">
                <img
                  src={studioBackdrop}
                  alt="Neo-Tokyo Vietsub Studio Widescreen Frame"
                  referrerPolicy="no-referrer"
                  className="w-full h-full object-cover opacity-90"
                />
              </div>
            )}

            {/* Measured contrast scrim for WCAG AA subtitle legibility */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/25 to-black/50 pointer-events-none" />

            {/* Top Sign Overlay (\an8 SignTop style cues) */}
            <div className="absolute top-4 inset-x-6 flex flex-col items-center pointer-events-none">
              <div className="w-full flex items-center justify-between text-[11px] font-mono text-slate-300/90 tabular-nums mb-2">
                <span>FILE: {videoTitle}</span>
                <span>
                  TIME: 00:00:{currentTime.toFixed(2).padStart(5, "0")} / 00:00:16.00
                </span>
              </div>

              {activeCues
                .filter((c) => c.style === "SignTop")
                .map((cue) => (
                  <div
                    key={cue.id}
                    className="px-4 py-1.5 bg-slate-950/85 border border-sky-400/60 rounded text-center shadow-lg"
                  >
                    <div className="text-xs font-mono font-semibold tracking-wider text-sky-300">
                      {cue.vietsubText}
                    </div>
                  </div>
                ))}
            </div>

            {/* Bottom Dialogue / Karaoke ASS Overlay (\an2 Default, CyberNeon, KaraokeFX) */}
            <div className="absolute bottom-5 inset-x-8 flex flex-col items-center text-center space-y-2 pointer-events-none">
              {activeCues
                .filter((c) => c.style !== "SignTop")
                .map((cue) => {
                  const progressRatio = Math.min(
                    1,
                    Math.max(
                      0,
                      (currentTime - cue.startSec) /
                        Math.max(0.2, cue.endSec - cue.startSec)
                    )
                  );
                  const words = cue.vietsubText.split(" ");
                  const highlightedCount = Math.ceil(
                    words.length * progressRatio
                  );

                  return (
                    <div key={cue.id} className="max-w-2xl space-y-1">
                      {showBilingual && (
                        <div className="text-xs text-slate-300/90 font-medium drop-shadow">
                          {cue.originalText}
                        </div>
                      )}

                      {cue.style === "KaraokeFX" ? (
                        <div className="text-lg sm:text-xl font-bold tracking-wide drop-shadow-[0_2px_4px_rgba(0,0,0,0.95)]">
                          {words.map((word, idx) => (
                            <span
                              key={idx}
                              className={
                                idx < highlightedCount
                                  ? "text-emerald-300 transition-colors"
                                  : "text-white/90"
                              }
                            >
                              {word}{" "}
                            </span>
                          ))}
                        </div>
                      ) : cue.style === "CyberNeon" ? (
                        <div className="text-lg sm:text-xl font-bold text-sky-200 drop-shadow-[0_2px_6px_rgba(14,165,233,0.65)]">
                          {cue.vietsubText}
                        </div>
                      ) : (
                        <div className="text-lg sm:text-xl font-semibold text-white drop-shadow-[0_2px_4px_rgba(0,0,0,0.95)]">
                          {cue.vietsubText}
                        </div>
                      )}

                      <div className="text-[11px] font-mono text-slate-400">
                        {cue.speaker} · Style: {cue.style} · {cue.effectTag}
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>

          {/* Interactive Timeline Scrubbar & Transport Controls */}
          <div className="p-4 bg-[#0B0F17] border-t border-slate-800/80 space-y-3">
            <div className="flex items-center gap-3">
              <button
                onClick={() => setIsPlaying(!isPlaying)}
                className="inline-flex items-center justify-center w-9 h-9 rounded-md bg-sky-500 hover:bg-sky-400 text-slate-950 transition-colors shrink-0"
                aria-label={isPlaying ? "Tạm dừng" : "Phát"}
              >
                {isPlaying ? (
                  <Pause className="w-4 h-4" />
                ) : (
                  <Play className="w-4 h-4 fill-current" />
                )}
              </button>

              <button
                onClick={() => {
                  setIsPlaying(false);
                  setCurrentTime(0.6);
                }}
                className="inline-flex items-center justify-center w-9 h-9 rounded-md bg-slate-800 hover:bg-slate-700 text-slate-200 transition-colors shrink-0"
                aria-label="Tua về đầu"
              >
                <RotateCcw className="w-4 h-4" />
              </button>

              <div className="flex-1">
                <input
                  type="range"
                  min={0}
                  max={duration}
                  step={0.1}
                  value={currentTime}
                  onChange={(e) => setCurrentTime(Number(e.target.value))}
                  className="w-full accent-sky-400 cursor-pointer"
                />
                <div className="flex justify-between text-[11px] font-mono text-slate-400 tabular-nums mt-0.5">
                  <span>00:00.00</span>
                  <span className="text-sky-400">
                    Playhead: {currentTime.toFixed(2)}s
                  </span>
                  <span>00:16.00</span>
                </div>
              </div>
            </div>

            {/* Visual Timeline Cue Blocks */}
            <div className="grid grid-cols-4 gap-1.5 pt-1">
              {cues.slice(0, 4).map((c) => {
                const isActive =
                  currentTime >= c.startSec && currentTime <= c.endSec;
                return (
                  <button
                    key={c.id}
                    onClick={() => setCurrentTime(c.startSec + 0.1)}
                    className={`p-2 rounded text-left border transition-colors ${
                      isActive
                        ? "bg-sky-950/60 border-sky-500/80 text-sky-200"
                        : "bg-[#111827] border-slate-800/90 text-slate-400 hover:border-slate-700"
                    }`}
                  >
                    <div className="text-[11px] font-mono tabular-nums text-sky-400">
                      {c.startSec.toFixed(1)}s – {c.endSec.toFixed(1)}s
                    </div>
                    <div className="text-xs text-slate-200 truncate mt-0.5">
                      {c.vietsubText}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right 5 Cols: Tier 5 Whisper STT + GPT-4o/Gemini Translation & ASS Export */}
        <div className="lg:col-span-5 bg-[#111827] border border-slate-800/90 rounded-lg p-5 flex flex-col justify-between space-y-4">
          <div className="space-y-4">
            <div>
              <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-sky-400" />
                Vietsub AI Backend (Whisper STT → Gemini/GPT-4o)
              </h2>
              <p className="text-xs text-slate-400 mt-1">
                Định tuyến qua Edge Gateway <span className="font-mono text-sky-400">/api/vietsub/ai-process</span> để dịch ngữ cảnh điện ảnh và sinh thẻ hiệu ứng .ASS tự động.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-3 text-xs">
              <div>
                <label className="block text-slate-300 mb-1 font-medium">
                  Ngôn Ngữ Gốc (STT)
                </label>
                <select
                  value={sourceLang}
                  onChange={(e) => setSourceLang(e.target.value)}
                  className="w-full px-3 py-2 bg-[#0B0F17] border border-slate-800 rounded-md text-slate-100 focus:outline-none focus:border-sky-500"
                >
                  <option value="ja-JP">Tiếng Nhật (Anime / J-Drama)</option>
                  <option value="zh-CN">Tiếng Trung (Donghua / Wuxia)</option>
                  <option value="ko-KR">Tiếng Hàn (K-Drama / Cinema)</option>
                  <option value="en-US">Tiếng Anh (Sci-Fi / Tech Doc)</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-300 mb-1 font-medium">
                  Preset Phong Cách .ASS
                </label>
                <select
                  value={stylePreset}
                  onChange={(e) =>
                    setStylePreset(
                      e.target.value as
                        | "CyberNeon"
                        | "KaraokeFX"
                        | "Default"
                        | "SignTop"
                    )
                  }
                  className="w-full px-3 py-2 bg-[#0B0F17] border border-slate-800 rounded-md text-slate-100 focus:outline-none focus:border-sky-500"
                >
                  <option value="CyberNeon">CyberNeon (Blur + Viền Sáng)</option>
                  <option value="KaraokeFX">KaraokeFX (Chạy Chữ \k)</option>
                  <option value="Default">Default (Chuẩn Điện Ảnh)</option>
                  <option value="SignTop">SignTop (Chú Thích Trên \an8)</option>
                </select>
              </div>
            </div>

            <div className="text-xs">
              <div className="flex items-center justify-between mb-1">
                <label className="text-slate-300 font-medium">
                  Kịch Bản / Transcript Đầu Vào (Hoặc Dán Thoại Phim)
                </label>
                <button
                  type="button"
                  onClick={() =>
                    setRawScriptInput(
                      `1. [00:00.5 - 00:04.0] Commander: クラウドフレアD1とR2の自動バインディングが完了しました。\n2. [00:04.2 - 00:08.0] AI Core: VietQR決済ストリームとTelegramミニアプリがリアルタイム同期中です。\n3. [00:08.2 - 00:12.0] Sign: SYSTEM STATUS: ALL 7 TIERS OPERATIONAL\n4. [00:12.2 - 00:16.0] Commander: 字幕オクトパスWASMで最高画質のベトナム語字幕を出力せよ！`
                    )
                  }
                  className="text-sky-400 hover:text-sky-300 whitespace-nowrap"
                >
                  Nạp kịch bản mẫu 2
                </button>
              </div>
              <textarea
                rows={5}
                value={rawScriptInput}
                onChange={(e) => setRawScriptInput(e.target.value)}
                className="w-full p-3 bg-[#0B0F17] border border-slate-800 rounded-md text-slate-100 font-mono text-xs leading-relaxed focus:outline-none focus:border-sky-500"
              />
            </div>

            <button
              onClick={handleRunAiVietsub}
              disabled={isAiProcessing}
              className="w-full py-2.5 px-4 bg-sky-500 hover:bg-sky-400 disabled:opacity-50 text-slate-950 font-semibold text-xs rounded-md transition-colors flex items-center justify-center gap-2 whitespace-nowrap"
            >
              <Sparkles className="w-4 h-4" />
              {isAiProcessing
                ? "Đang Dịch AI & Đồng Bộ Timeline .ASS..."
                : "Chạy AI Vietsub & Đồng Bộ Timeline (Gemini 3.8 Flash)"}
            </button>
          </div>

          <div className="pt-4 border-t border-slate-800/80 space-y-2.5">
            <div className="text-xs font-medium text-slate-300">
              Xuất Bản Phụ Đề (.ASS) & Kết Xuất FFmpeg Worker (Tier 5 → R2)
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              <button
                onClick={handleDownloadAss}
                className="inline-flex items-center justify-center gap-2 py-2 px-3 bg-slate-800 hover:bg-slate-700 text-slate-100 text-xs font-medium rounded-md transition-colors whitespace-nowrap"
              >
                <Download className="w-3.5 h-3.5" />
                Tải File .ASS
              </button>

              <button
                onClick={handlePushToFfmpegR2}
                disabled={isExportingR2}
                className="inline-flex items-center justify-center gap-2 py-2 px-3 bg-emerald-500 hover:bg-emerald-400 disabled:opacity-50 text-slate-950 text-xs font-semibold rounded-md transition-colors whitespace-nowrap"
              >
                <Film className="w-3.5 h-3.5" />
                {isExportingR2 ? "Đang Render..." : "Render Hardsub R2"}
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Editable ASS Subtitle Timeline Table */}
      <div className="bg-[#111827] border border-slate-800/90 rounded-lg divide-y divide-slate-800/80">
        <div className="p-4 flex items-center justify-between gap-4">
          <div>
            <h3 className="text-sm font-semibold text-slate-100">
              Bảng Điều Chỉnh Timeline Phụ Đề .ASS (Live Sync với SubtitlesOctopus)
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Chỉnh sửa trực tiếp lời dịch, thời gian hoặc thẻ hiệu ứng ASS override — thay đổi phản hồi tức thì trên khung hình video.
            </p>
          </div>
          <button
            onClick={handleAddCue}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-sky-500 hover:bg-sky-400 text-slate-950 text-xs font-semibold rounded-md transition-colors whitespace-nowrap"
          >
            <Plus className="w-3.5 h-3.5" />
            Thêm Dòng Phụ Đề
          </button>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-800/80 text-xs text-slate-400 bg-[#0B0F17]/50">
                <th className="py-2.5 px-3 font-medium">Bắt Đầu (s)</th>
                <th className="py-2.5 px-3 font-medium">Kết Thúc (s)</th>
                <th className="py-2.5 px-3 font-medium">Nhân Vật</th>
                <th className="py-2.5 px-3 font-medium">Style .ASS</th>
                <th className="py-2.5 px-3 font-medium">Thẻ Override</th>
                <th className="py-2.5 px-3 font-medium">Lời Dịch Tiếng Việt (Vietsub)</th>
                <th className="py-2.5 px-3 font-medium text-right">Xoá</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-xs">
              {cues.map((cue) => (
                <tr key={cue.id} className="hover:bg-slate-800/25">
                  <td className="py-2 px-3 w-24">
                    <input
                      type="number"
                      step="0.1"
                      value={cue.startSec}
                      onChange={(e) =>
                        handleUpdateCueField(
                          cue.id,
                          "startSec",
                          Number(e.target.value)
                        )
                      }
                      className="w-20 px-2 py-1 bg-[#0B0F17] border border-slate-800 rounded font-mono tabular-nums text-slate-200"
                    />
                  </td>
                  <td className="py-2 px-3 w-24">
                    <input
                      type="number"
                      step="0.1"
                      value={cue.endSec}
                      onChange={(e) =>
                        handleUpdateCueField(
                          cue.id,
                          "endSec",
                          Number(e.target.value)
                        )
                      }
                      className="w-20 px-2 py-1 bg-[#0B0F17] border border-slate-800 rounded font-mono tabular-nums text-slate-200"
                    />
                  </td>
                  <td className="py-2 px-3 w-36">
                    <input
                      type="text"
                      value={cue.speaker}
                      onChange={(e) =>
                        handleUpdateCueField(cue.id, "speaker", e.target.value)
                      }
                      className="w-full px-2 py-1 bg-[#0B0F17] border border-slate-800 rounded text-slate-200"
                    />
                  </td>
                  <td className="py-2 px-3 w-36">
                    <select
                      value={cue.style}
                      onChange={(e) =>
                        handleUpdateCueField(cue.id, "style", e.target.value)
                      }
                      className="w-full px-2 py-1 bg-[#0B0F17] border border-slate-800 rounded text-sky-300 font-mono"
                    >
                      <option value="CyberNeon">CyberNeon</option>
                      <option value="KaraokeFX">KaraokeFX</option>
                      <option value="Default">Default</option>
                      <option value="SignTop">SignTop</option>
                    </select>
                  </td>
                  <td className="py-2 px-3 w-44">
                    <input
                      type="text"
                      value={cue.effectTag}
                      onChange={(e) =>
                        handleUpdateCueField(cue.id, "effectTag", e.target.value)
                      }
                      className="w-full px-2 py-1 bg-[#0B0F17] border border-slate-800 rounded font-mono text-amber-300"
                    />
                  </td>
                  <td className="py-2 px-3">
                    <input
                      type="text"
                      value={cue.vietsubText}
                      onChange={(e) =>
                        handleUpdateCueField(
                          cue.id,
                          "vietsubText",
                          e.target.value
                        )
                      }
                      className="w-full px-2.5 py-1 bg-[#0B0F17] border border-slate-800 rounded text-slate-100"
                    />
                  </td>
                  <td className="py-2 px-3 text-right">
                    <button
                      onClick={() => handleDeleteCue(cue.id)}
                      className="p-1.5 text-slate-400 hover:text-rose-400 rounded transition-colors"
                      aria-label="Xoá dòng phụ đề"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Bottom 4 App/Web Dev Engine Modules (S1 - S4 in L1 Diagram) */}
      <div className="bg-[#111827] border border-slate-800/90 rounded-lg divide-y divide-slate-800/80">
        <div className="p-4 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h3 className="text-sm font-semibold text-slate-100">
              App / Web Dev Engine & SDK Packaging Suite (Tier 1 WASMStudio)
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Đóng gói trình phát phụ đề WebAssembly thành Web SDK, ứng dụng Desktop/Mobile hoặc cổng Webhook.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-1 bg-[#0B0F17] p-1 rounded-md border border-slate-800">
            <button
              onClick={() => setActiveDevModule("sdk")}
              className={`inline-flex items-center gap-1.5 px-3 py-1.5 text-xs rounded transition-colors whitespace-nowrap ${
                activeDevModule === "sdk"
                  ? "bg-sky-500 text-slate-950 font-semibold"
                  : "text-slate-300 hover:text-white"
              }`}
            >
              <Code2 className="w-3.5 h-3.5" />
              S1. Web SDK (@cyber/vietsub-sdk)
            </button>
            <button
              onClick={() => setActiveDevModule("packager")}
              className={`inline-flex items-center gap-1.5 px-3 py-1.5 text-xs rounded transition-colors whitespace-nowrap ${
                activeDevModule === "packager"
                  ? "bg-sky-500 text-slate-950 font-semibold"
                  : "text-slate-300 hover:text-white"
              }`}
            >
              <Package className="w-3.5 h-3.5" />
              S2. App Packager (PWA / Tauri)
            </button>
            <button
              onClick={() => setActiveDevModule("builder")}
              className={`inline-flex items-center gap-1.5 px-3 py-1.5 text-xs rounded transition-colors whitespace-nowrap ${
                activeDevModule === "builder"
                  ? "bg-sky-500 text-slate-950 font-semibold"
                  : "text-slate-300 hover:text-white"
              }`}
            >
              <Sliders className="w-3.5 h-3.5" />
              S3. Interactive Video Web Builder
            </button>
            <button
              onClick={() => setActiveDevModule("webhook")}
              className={`inline-flex items-center gap-1.5 px-3 py-1.5 text-xs rounded transition-colors whitespace-nowrap ${
                activeDevModule === "webhook"
                  ? "bg-sky-500 text-slate-950 font-semibold"
                  : "text-slate-300 hover:text-white"
              }`}
            >
              <Webhook className="w-3.5 h-3.5" />
              S4. Webhook & REST API Gateway
            </button>
          </div>
        </div>

        <div className="p-5">
          {activeDevModule === "sdk" && (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-300 font-medium">
                  Mã Tích Hợp Nhanh @cyber/vietsub-sdk (Tự động nạp .ASS & Font từ Cloudflare R2)
                </span>
                <button
                  onClick={handleCopySdk}
                  className="inline-flex items-center gap-1.5 px-3 py-1 text-xs font-medium bg-slate-800 hover:bg-slate-700 text-sky-300 rounded transition-colors whitespace-nowrap"
                >
                  <Copy className="w-3.5 h-3.5" />
                  {copiedCode ? "Đã sao chép!" : "Sao chép mã SDK"}
                </button>
              </div>
              <pre className="p-4 bg-[#0B0F17] border border-slate-800 rounded-md text-xs font-mono text-sky-200 overflow-x-auto leading-relaxed">
                {sdkSnippet}
              </pre>
            </div>
          )}

          {activeDevModule === "packager" && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
              {[
                {
                  id: "tauri",
                  title: "Tauri v2 Desktop (Windows / macOS / Linux)",
                  desc: "Tích hợp lõi Rust + WebView2 kết xuất phụ đề WASM với mức tiêu thụ RAM giảm 65% so với Electron.",
                  artifact: "cybersub-studio-x64.msi · 14.2 MB",
                },
                {
                  id: "pwa",
                  title: "Cloudflare Pages PWA + Service Worker",
                  desc: "Cài đặt trực tiếp từ trình duyệt, lưu đệm tệp .wasm và font chữ Karaoke vào CacheStorage ngoại tuyến.",
                  artifact: "manifest.webmanifest · sw-wasm.js",
                },
                {
                  id: "capacitor",
                  title: "Mobile Native Wrapper (Android APK / iOS IPA)",
                  desc: "Đồng bộ trực tiếp với Telegram Mini App WebApp SDK và thông báo đẩy qua Bot API.",
                  artifact: "cybersub-mobile-release.apk · 22.8 MB",
                },
              ].map((pkg) => (
                <div
                  key={pkg.id}
                  onClick={() =>
                    setPackagerTarget(pkg.id as "tauri" | "pwa" | "capacitor")
                  }
                  className={`p-4 rounded-lg border cursor-pointer transition-colors ${
                    packagerTarget === pkg.id
                      ? "bg-sky-950/30 border-sky-500/80"
                      : "bg-[#0B0F17] border-slate-800"
                  }`}
                >
                  <div className="font-semibold text-slate-100">{pkg.title}</div>
                  <p className="text-slate-400 mt-1.5 leading-relaxed">
                    {pkg.desc}
                  </p>
                  <div className="mt-3 font-mono text-sky-400 tabular-nums">
                    Output: {pkg.artifact}
                  </div>
                </div>
              ))}
            </div>
          )}

          {activeDevModule === "builder" && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
              <div className="p-4 bg-[#0B0F17] border border-slate-800 rounded-lg space-y-2">
                <label className="block text-slate-300 font-medium">
                  Giới Hạn Bộ Nhớ WASM SubtitlesOctopus Heap (MB)
                </label>
                <input
                  type="range"
                  min={256}
                  max={2048}
                  step={256}
                  value={wasmMemoryMb}
                  onChange={(e) => setWasmMemoryMb(Number(e.target.value))}
                  className="w-full accent-sky-400"
                />
                <div className="font-mono text-sky-400 tabular-nums">
                  Đang cấp phát: {wasmMemoryMb} MB (Đồng bộ lên SDK)
                </div>
              </div>

              <div className="p-4 bg-[#0B0F17] border border-slate-800 rounded-lg space-y-2">
                <label className="block text-slate-300 font-medium">
                  Tốc Độ Khung Hình Kết Xuất Canvas (Target FPS)
                </label>
                <div className="flex items-center gap-2 pt-1">
                  {[30, 60, 120].map((fps) => (
                    <button
                      key={fps}
                      onClick={() => setRenderFps(fps)}
                      className={`px-3 py-1.5 rounded font-mono transition-colors ${
                        renderFps === fps
                          ? "bg-sky-500 text-slate-950 font-semibold"
                          : "bg-slate-800 text-slate-300"
                      }`}
                    >
                      {fps} FPS
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {activeDevModule === "webhook" && (
            <div className="p-4 bg-[#0B0F17] border border-slate-800 rounded-lg text-xs space-y-2 font-mono">
              <div className="text-slate-300">
                POST /api/vietsub/ai-process · POST /api/vietsub/export-hardsub
              </div>
              <div className="text-slate-400">
                Header bắt buộc: X-Cyber-Signature (HMAC-SHA256) · Định tuyến qua Cloudflare Worker Central Dispatcher (Tier 3)
              </div>
              <div className="text-emerald-400">
                Trạng thái kết nối: Sẵn sàng nhận gói tin JSON Timeline & trả về đường dẫn R2 Bucket.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
